config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
# Represents a person in a contact list
class Contact < ApplicationRecord
  validates :phone_number, format: { with: /\A\d{10,11}\z/, message: "Integers only." }
  validates_uniqueness_of :phone_number, message: 'must be unique.'

  validates :first_name, format: { with: /\A[A-Za-z]+-*\s*[A-Za-z]+\z/, message: "Names can only contain letters, dashes, and spaces." }

  validates :last_name, format: { with: /\A[A-Za-z]+-*\s*[A-Za-z]+\z/, message: "Names can only contain letters, dashes, and spaces." }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    filter = params[:filter]

    # These could use scopes, but that sounds excessive for now. Maybe in the future.
    @contacts =
      case filter
      when 'alphabetical'
        Contact.order(first_name: :asc)
      when 'reverse_alphabetical'
        Contact.order(first_name: :desc)
      when 'creation_date'
        Contact.order(created_at: :asc)
      when 'reverse_creation_date'
        Contact.order(created_at: :desc)
      else
        Contact.all
      end
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy!

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <p>
    <strong>First name:</strong>
    <%= contact.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= contact.last_name %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= contact.phone_number %>
  </p>

</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Show this contact", @contact %> |
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contacts</h1>

<div id="contacts">
  <% @contacts.each do |contact| %>
    <%= render contact %>
    <p>
      <%= link_to "Show this contact", contact %>
    </p>
  <% end %>
</div>

<%= link_to "New contact", new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contact %>

<div>
  <%= link_to "Edit this contact", edit_contact_path(@contact) %> |
  <%= link_to "Back to contacts", contacts_path %>

  <%= button_to "Destroy this contact", @contact, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactsList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>